name: Bash script analysis

on:
  push:
    branches: [main]
  pull_request:

jobs:
  bash-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ShellCheck and shfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          echo "Linting with ShellCheck..."
          shellcheck janus-init.sh
          shellcheck janus-deinit.sh
