name: Scan Docker images with Grype

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  scan-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Run Janus init.sh script
      run: bash ./init.sh

    - name: Scan built images with Grype
      run: |
        echo "Scanning Docker images created by init.sh..."
        for image in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep janus); do
          echo "Scanning $image..."
          grype "$image" --fail-on high
        done
